### PR TITLE
Updated frontend to set the placeholder image if we do not pass a ima…

### PR DESCRIPTION
**Pull request by NHarviel**
…ge url

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks NHarviel, I'll review the changes right away!

**Review by ghost — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by NHarviel** [comment]
Screen Shot 2023-01-06 at 4 22 36 PM

**Review by ghost — APPROVED** [review]
Excellent job NHarviel! You're now able to merge the PR.

**Pull request merged**
